{% set name = "netket" %}
{% set version = "3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netket-{{ version }}.tar.gz
  sha256: ff53f2b929f8b2841c90c2ce1822aaa38388cdcea7c4eca6ee17e14201a4fcbe

build:
  number: 0
  noarch: python
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python >=3.8
    - hatchling >=1.8.0
    - pip
  run:
    - python >=3.8
    - numpy >=1.19
    - scipy >=1.5.3
    - python-igraph >=0.9.8
    - jax >=0.3.20
    - jaxlib >0.3.20
    - flax >=0.6.1
    - optax >=0.1.3
    - mpi4py >=3.0.1
    - mpi4jax >=0.3.8
    - numba4jax >=0.0.10
    - numba >=0.52.0
    - orjson >=3.4
    - tqdm >=4.56.2
    - plum-dispatch >=1.5.1

test:
  commands:
    - |
    # remove this line once netket depends on igraph instead of python-igraph
    - pip install python-igraph
    - pip check

    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

    - python -c "import netket"
  requires:
    - pip

about:
  home: https://www.netket.org
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Machine Learning for Many-Body Quantum Systems
  description: |
    NetKet is an open-source project delivering cutting-edge methods 
    for the study of many-body quantum systems with artificial neural 
    networks and machine learning techniques. It is a Python library 
    built on C++ primitives.
  doc_url: https://www.netket.org/documentation.html
  dev_url: https://github.com/netket/netket

extra:
  recipe-maintainers:
    - PhilipVinc
    - gcarleo
