{% set name = "netket" %}
{% set version = "2.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/netket/netket/archive/v{{ version }}.tar.gz
  sha256: 881ae8605a829364b2116bc4398084766b24e2cd8958d0cb2b85595650e7bfd6

build:
  number: 0
  skip: true  # [win or py<37]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv --install-option=--cmake-args='-DNETKET_USE_LAPACK=OFF -DCMAKE_BUILD_TYPE=Release -DNETKET_USE_OPENMP=ON -DNETKET_USE_BLAS=ON -DNETKET_USE_SLEEF=ON'"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.12
    - ninja
  host:
    - pip
    - python
    - mpich
    - libblas
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - numpy >=1.16
    - python 
    - scipy >=1.2.1
    - numba >=0.48
    - mpich
    - mpi4py
    - tqdm

test:
  imports:
    - netket

about:
  home: https://www.netket.org
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Machine Learning for Many-Body Quantum Systems'
  description: |
    NetKet is an open-source project delivering cutting-edge methods 
    for the study of many-body quantum systems with artificial neural 
    networks and machine learning techniques. It is a Python library 
    built on C++ primitives.
  doc_url: https://www.netket.org/documentation.html
  dev_url: https://github.com/netket/netket

extra:
  recipe-maintainers:
    - PhilipVinc
    - gcarleo
